version: '3.8'
services:
  mongodb:
    image: mongo
    env_file:
      - ./env/mongo.env
    volumes:
      - mongo-data:/data/db
  backend:
    build: ./backend
    ports:
      - '80:80'
    env_file:
      - ./env/backend.env
    volumes:
      - logs:/app/logs
      - ./backend:/app/backend
      - /app/node_modules
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    env_file:
      - ./env/frontend.env
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    stdin_open: true
    tty: true

volumes:
  mongo-data:
  logs:
